# github.com/go-task/task
version: '2'

include:
  services: ./services

vars:
  GREETING: Sample Usage for custom pypi

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  mypypi-install-raw:
    cmds:
      - pipenv run pip install --extra-index-url http://localhost:8081 refstore

  deps-install:
    desc: install dependancies
    cmds:
      - pipenv install --skip-lock
